server:
	do-daemonize: no
	interface: 0.0.0.0

# XXX(beagles) figure out how to insert acl for the user's config. We can't
# merge it here because it will just obliterate what's already there.

	log-queries: no
	hide-identity: yes
	hide-version: yes
	hide-trustanchor: yes
	harden-short-bufsize: yes
	harden-large-queries: yes
        access-control: 172.50.0.0/24 allow
        access-control: 172.28.0.0/24 allow
        access-control: 10.217.0.0/16 allow
# If accessed through MetalLB, then we need to allow the kube-proxy range.
        access-control: 100.64.0.0/10 allow

	unblock-lan-zones: yes
	insecure-lan-zones: yes
        verbosity: 4

#
# FUTURE: TLS (not currently implemented in available releases)
#
	rrset-cache-size: 100m
	msg-cache-size: 50m

remote-control:
	control-enable: no

forward-zone:
    name: "."
    forward-addr: 10.11.5.19
    forward-addr: 10.2.32.1

