// TODO: replace with a per pod configuration to support rndc-key-per-bind instance.
key "rndc-key" {
        algorithm hmac-sha256;
        secret "oVkePs22V9Tkiam4c34ZVsWc9LlY5kyF01lySYvw8RQ="; # XXX- replace with init container derived value.
};

// The current PODs bind9 address is set by the initcontainer.
// WARNING: if the required information is not available
// the bind service will be configured to listen to all IPv4
// addresses
controls {
        inet * allow { {{.AllowCIDR}}; } keys { "rndc-key"; };
};
